growurcoins/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
 path('', views.home, name='home'),
 path('about/', views.about, name='about'),
 path('growurcoins/', views.grow_index, name='index'), #shows the index of all Ads
 path('growurcoins/<int:ad_id>', views.grow_details, name='details'),   #Details of a specific Ad
 path('growurcoins/new', views.grow_new, name='new'), # url to show "create ad" form
 path('growurcoins/create', views.grow_create, name='create'), #this will save the "create ad" form into the database
 path('growurcoins/<int:ad_id>/delete', views.grow_delete, name='delete'),   #Delete a specific Ad
 path('growurcoins/<int:ad_id>/add_photo/', views.add_photo, name='add_photo'), #add photo in new 
 path('accounts/signup/', views.signup, name='signup'),
 path('growurcoins/listing/<str:category>', views.grow_category, name='details'), 
 path('growurcoins/home', views.grow_home, name='home'), #shows the home of all categories
 path('growurcoins/<int:ad_id>/add_to_cart', views.grow_add_to_cart, name='add_to_cart'), #this will save the "ad" into the logged in user's cart model in the database 
 path('growurcoins/cart', views.grow_cart, name='cart'), #this will take us to the cart  
 path('growurcoins/checkout', views.grow_checkout, name='checkout'), #this will checkout the cart
 path('growurcoins/delete_cart', views.grow_delete_cart, name='delete_cart'), #this will delete the cart
 path('growurcoins/search', views.grow_search, name='search'),


 
]

main_app/models.py
from sre_parse import CATEGORIES
from unicodedata import category
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

#Relationships: #always put the FK on many side.
# ONE Cart will have MANY Ads (FK = cart_id)
# ONE User will have ONE Cart
# ONE User will have MANY Ads (FK = user_id)
# ONE User will have MANY REVIEWS(FK = user_id)
CATEGORIES = (
    "Green Beans",
    "Lettuce", "Peas", "Carrots", "Cucumbers",
)

class Ad(models.Model): #this model is missing the FK, user_id from the usertable
    ad_title = models.CharField(max_length=15)
    coins = models.IntegerField()
    description = models.TextField(max_length=250)
    offer_date = models.DateField()
    expiry_date = models.DateField()
    stock_inventory = models.IntegerField()
    picture_one = models.URLField(max_length=200)
    category = models.CharField(max_length=200)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)   # <-- one user can have many ads 
    # default=1 <-- this asigns a defaul user id of '1' to existing ads

    def __str__(self):
        return self.ad_title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'cat_id': self.id})

class Photo(models.Model):
    url = models.CharField(max_length=200)
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    def __str__(self):
        return f"Photo for ad_id: {self.ad_id} @{self.url}"
            
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    #quantity = models.IntegerField(default=1)
    #total_cost = models.IntegerField(default=1)

class Reviews(models.Model):
    ratings = models.IntegerField()
    feedback = models.TextField(max_length=250)

main_app/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

from fileinput import filename
from django.shortcuts import render, redirect
from .models import Ad
import datetime
from .models import Cart


# Add the following import
from django.http import HttpResponse

#import boto3 for add photos
import uuid
import boto3
from .models import Ad, Photo

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

#amazon bucket
S3_BASE_URL = 'https://s3.us-east-2.amazonaws.com/'
BUCKET= 'growurcoinsbucket'

# Define the home view
def home(request):
    return HttpResponse('<h1>Hello /ᐠ｡‸｡ᐟ\ﾉ</h1>')

def about(request):
    return render(request, 'about.html')
#   return HttpResponse('<h1>About the GrowUrCoins</h1>')

#controller to show all Ads
def grow_index(request):
    ad = Ad.objects.all()
    print(ad)
    return render(request, 'growurcoins/index.html', { 'ad': ad })

#controller to show specific Ad
def grow_details(request, ad_id):
    print("incoming wild card value is", ad_id)
    ad = Ad.objects.get(id=ad_id)
    print(ad)
    print("The ad to be rendered is", ad)
    return render(request, 'growurcoins/detail.html', {"ad": ad} )
    # return HttpResponse("done")

#controller to show listing categories
def grow_category(request, category):
    print("incoming wild card value is", category)
    Ads_in_category = Ad.objects.filter(category__contains=category)
    print(Ads_in_category)
    # ad = Ad.objects.get(id=ad_id)
    # print(ad)
    # print("The ad to be rendered is", ad)
    return render(request, 'growurcoins/listing-category.html', {"Ads_in_category":Ads_in_category})
    # return HttpResponse("done")

#controller to create a form for New Ad
def grow_new(request):
    return render(request, 'growurcoins/new.html')
    # return HttpResponse("done")

#controller to create a New Ad in the database
def grow_create(request):
     print("incoming form data", request.POST)
     myad = Ad.objects.create(ad_title=request.POST['ad_title'], 
                       coins=request.POST['coins'], 
                       description=request.POST['description'],
                       offer_date = request.POST['offer_date'],
                       expiry_date = request.POST['expiry_date'],
                       stock_inventory = request.POST['stock_inventory'],
                       category = request.POST['category'],
                       address = request.POST['address'],
                       city = request.POST['city'],
                       postal_code = request.POST['postal_code'],
                       user = request.user
                       )
      
     photo_file = request.FILES.get('photo-file',None)
     print(photo_file, "*****")
     if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        filename = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, filename)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{filename}"
            print(url, filename,myad.id, "*************************")
            Photo.objects.create(url=url, ad_id=myad.id)
      
            # we can assign to cat_id or cat (if you have a cat object)
        except:
            print('An error occurred uploading file to S3')
     return redirect('/growurcoins') #redirect index page.

#controller to add an Ad to a Cart
def grow_add_to_cart(request, ad_id):
     print("incoming ", request.POST)
     mycart = Cart.objects.create(
                        user = request.user,
                        ad = Ad.objects.get(id = ad_id)
                        )
     print("Add has been added to the cart!!!") 
     return redirect('/growurcoins') #redirect index page.

######-------------------------------------------------------
#controller to view all items in Cart
def grow_cart(request):                    
    add_ids_in_cart = Cart.objects.filter(user_id = request.user.id)
    myads = []
    for item in add_ids_in_cart:
        myads.append(Ad.objects.get(id=item.ad_id))

    return render(request, 'growurcoins/cart.html', {"myads": myads} ) #redirect cart page.

######------------------------------------------------------------
#controller to delete the Ad
def grow_delete(request, ad_id):
    ad = Ad.objects.get(id=ad_id)
    ad.delete()
    return render(request, 'growurcoins/delete.html', {"ad": ad})

#controller to add photo
def add_photo(request, ad_id):
    #get photo sent by frontend 

    return redirect('detail', ad_id=ad_id)

#controller to home categories
def grow_home(request,):
    listCategories = Ad.objects.values_list('category', flat=True).distinct()
    print(listCategories)
    return render(request, 'growurcoins/home.html',{"listCategories" : listCategories})

def grow_checkout(request,):
    print("user_id", request.user.id) 
    add_ids_in_cart = Cart.objects.filter(user_id = request.user.id)
    myads = []
    
    for item in add_ids_in_cart:
        myads.append(Ad.objects.get(id=item.ad_id))
        
    print(myads)
    ad_coins = [] 
    for ad in myads:
        ad_coins.append(ad.coins)
        print(ad.coins)
    total_coins = sum(ad_coins)
    print(total_coins)


    return render(request, 'growurcoins/thankyou.html', {"total_coins" : total_coins }  )

def grow_delete_cart(request, ):
    print("going back to home menu") 
    print("user_id", request.user.id) 
    add_ids_in_cart = Cart.objects.filter(user_id = request.user.id)
    myads = []
    
    for item in add_ids_in_cart:
        myads.append(Ad.objects.get(id=item.ad_id))
        print("_______________")
        print(item.ad_id)

    for ad in add_ids_in_cart:
        delete_ad = Ad.objects.get(id=ad.ad_id)
        delete_ad.delete()
        print(ad.ad_id)

    print(myads)
    
    return redirect('/growurcoins') #redirect index page.

def grow_search(request):
    if request.method == 'POST':
        searched = request.POST['search']
        Ads = Ad.objects.filter(ad_title__contains=searched)
        return render(request, 'growurcoins/search.html', {'searched': searched, 'Ads': Ads})
    else:
        return redirect('/growurcoins/home') #redirect home page.

    
#####---------

    # def grow_delete(request, ad_id):
    # ad = Ad.objects.get(id=ad_id)
    # ad.delete()
    # return render(request, 'growurcoins/delete.html', {"ad": ad})

main_app/templates/growurcoins/cart.html
{% extends 'base.html' %} {% block content %}
<h6 class="green-text text-darken-3">My Cart</h6>

<div class="card">
  {%for ad in myads %}
  <div class="card-content">
    <span class="card-title">{{ ad.ad_title }}</span>

    <p>Cuisine: {{ ad.coins}}</p>
    <p>Description: {{ ad.description }}</p>
    <p>Coins: {{ ad.coins }}</p>
    <p>Description: {{ ad.description }}</p>
    <p>Offer Date: {{ ad.offer_date }}</p>
    <p>Expiry Date: {{ ad.expiry_date }}</p>
    <p>Stock: {{ ad.stock_inventory }}</p>
    <p>Category: {{ ad.category }}</p>
    <p>Address: {{ ad.address }}</p>
    <p>City: {{ ad.city }}</p>
    <p>Postal Code: {{ ad.postal_code }}</p>
    {% for photo in ad.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.url}}" />
    {% empty %} {% endfor %}{% endfor %} {% if user.is_authenticated %}
  </div>
</div>
<div class="card-action">
  <a href="{% url 'checkout' %}" class="green-text text-darken-3">checkout</a>
</div>
{% endif %}{% endblock %}

main_app/templates/growurcoins/delete.html
{% extends 'base.html' %}
{% block content %}

<h6 class="green-text text-darken-3" > Are you sure you want to delete {{ ad.ad_title }}</h6>

<form method="POST" action='{{ad.id}}/delete'>
    {% csrf_token %}
     <!-- <button>Delete</button> -->
     <a class="green-text text-darken-3" href="{% url 'index' %}">Delete</a>  
     
   </form>

{% endblock %}

main_app/templates/growurcoins/detail.html
{% extends 'base.html' %} {% block content %}

<h6 class="green-text text-darken-3">Ad Details</h6>

<div class="card">
  <div class="card-content">
    <span class="card-title">{{ ad.ad_title }}</span>

    <p>Cuisine: {{ ad.coins}}</p>
    <p>Description: {{ ad.description }}</p>
    <p>Coins: {{ ad.coins }}</p>
    <p>Description: {{ ad.description }}</p>
    <p>Offer Date: {{ ad.offer_date }}</p>
    <p>Expiry Date: {{ ad.expiry_date }}</p>
    <p>Stock: {{ ad.stock_inventory }}</p>
    <p>Category: {{ ad.category }}</p>
    <p>Address: {{ ad.address }}</p>
    <p>City: {{ ad.city }}</p>
    <p>Postal Code: {{ ad.postal_code }}</p>

    {% for photo in ad.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.url}}" />
    {% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}

    {% if user.is_authenticated %}
    <div class="card-action">
      <a href="{% url 'add_to_cart' ad.id %}" class="green-text text-darken-3">Add To My Cart</a>      
    </div>
    <div class="card-action">
      <a href="{% url 'delete' ad.id %}" class="green-text text-darken-3">Delete Ad</a>     
    </div>
    <br>
    {% else %}
    <p>Please Log In to add this item to your Cart</p>
    {% endif %}
  </div>
</div>

{% endblock %}

main_app/templates/growurcoins/home.html
{% extends 'base.html' %} {% block content %} {% for category in listCategories%}
<a href="/growurcoins/listing/{{category}}">
  <div class="card">
    <div class="card-content">
      <span class="card-title"> {{category}} </span>
    </div>
  </div>
</a>
{% endfor %} {% endblock %}

main_app/templates/growurcoins/index.html
{% extends 'base.html' %} {% block content %}

<h6 class="green-text text-darken-3">View All the Ad Listings</h6>
<form method="POST" action="{% url 'search' %}">
  {% csrf_token %}
  <div class="input-field searchbar">
    <input
      class="search--input"
      id="search"
      type="search"
      required
      name="search"
    />

    <!-- <i class="material-icons pink-text ">close</i> -->
    <button class="search--button" type="submit">Search</button>
  </div>
</form>
{% for Ad in ad %}
<div class="card">
  <div class="card-content">
    <a href="/growurcoins/{{ Ad.id }}">
      <span class="card-title">{{ Ad.ad_title }}</span>
      <p>Coins: {{ Ad.coins }}</p>
      <p>Description: {{ Ad.description }}</p>
      <p>Offer Date: {{ Ad.offer_date }}</p>
      <p>Expiry Date: {{ Ad.expiry_date }}</p>
      <p>Stock: {{ Ad.stock_inventory }}</p>
      <p>Category: {{ Ad.category }}</p>
      <p>Address: {{ Ad.address }}</p>
      <p>City: {{ Ad.city }}</p>
      <p>Postal Code: {{ Ad.postal_code }}</p>
    </a>
  </div>
</div>
{% endfor %} {% endblock %}

main_app/templates/growurcoins/listing-category.html
{% extends 'base.html' %} {% block content %}

<h1>Ad Details</h1>
{% for ad in Ads_in_category %}
<a href="/growurcoins/{{ ad.id }}">
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ ad.ad_title }}</span>
    <p>Coins: {{ ad.coins }}</p>
    <p>Offer Date: {{ ad.offer_date }}</p>
    <p>Expiry Date: {{ ad.expiry_date }}</p>
    <p>Stock: {{ ad.stock_inventory }}</p>

    {% for photo in ad.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.url}}" />
    {% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %} {%endfor%}
</a>
  </div>
</div>

{% endblock %}

main_app/templates/growurcoins/new.html
  {% extends 'base.html' %} 
  {% block content %} 

    <h6 class="green-text text-darken-3">Please Create your Ad:</h6>
    <form
      method="POST"
      action="/growurcoins/create"
      enctype="multipart/form-data">

      {% csrf_token %}
      <!-- making sure it is not a rando sending infor to your form data -->
      <br />
      <label for="ad_title">Ad Title: </label>
      <br />
      <input name="ad_title" placeholder="Please enter the title of your ad"/>
      <br />
      <br />

      <label for="coins">Coins: </label>
      <br />
      <input name="coins" placeholder="Please enter the coins granted" /><br />
      <br />

      <label for="description">Description: </label>
      <br />
      <textarea name="description" placeholder="Please enter the description">
      </textarea>
      <br />
      <br />

      <label for="offer_date">Offer Date: </label>
      <br />
      <input
        name="offer_date"
        type="date"
        placeholder="Please enter the offer date of your ad"
      />
      <br />
      <br />
      <br />

      <label for="expiry_date">Expiry Date: </label>
      <br />
      <input
        name="expiry_date"
        type="date"
        placeholder="Please enter the expiry date of your ad"
      />
      <br />
      <br />
      <br />

      <label for="stock_inventory">Inventory: </label>
      <br />
      <input name="stock_inventory" placeholder="Please enter the inventory" />
      <br />
      <br />
      <br />
    
      <label for="category">Category: </label>
      <select name="category" id="category">
        <option value="P">Please choose an option</option>
        <option value="Lettuce">Lettuce</option>
        <option value="Green Beans">Green Beans</option>
        <option value="Peas">Peas</option>
        <option value="Carrots">Carrots</option>
        <option value="Cucumbers">Cucumbers</option>
        <option value="Kale">Kale</option>
        <option value="Tomatoes">Tomatoes</option>
      </select>
      
      <label for="address">Address: </label>
      <br />
      <input name="address" placeholder="Please enter the address" />
      <br />
      <br />
      <br />
      <br />
      <br />

      <label for="city">City: </label>
      <br />
      <input name="city" placeholder="Please enter the city" />
      <br />
      <br />
      <br />

      <label for="postal_code">Postal Code: </label>
      <br />
      <input name="postal_code" placeholder="Please enter the postal code" />
      <br />
      <br />
      <br />

      <input type="file" name="photo-file" />
      <br /><br />

      <button type="submit">Submit Ad</button>
    </form>

    {% endblock %}

main_app/templates/growurcoins/search.html
{% extends 'base.html' %} {% block content %}

<h6 class="green-text text-darken-3">View All the Ad Listings</h6>

<form method="POST" action="{% url 'search' %}">
  {% csrf_token %}
  <div class="input-field searchbar">
    <input
      id="search"
      type="search"
      required
      name="search"
      value="{{searched}}"
      placeholder="Search"
      class="search--input"
    />

    <!-- <i class="material-icons pink-text ">close</i> -->
    <button class="search--button" type="submit">Search</button>
  </div>
</form>

{% for Ad in Ads %}
<div class="card">
  <div class="card-content">
    <a href="/growurcoins/{{ Ad.id }}">
      <span class="card-title">{{ Ad.ad_title }}</span>
      <p>Coins: {{ Ad.coins }}</p>
      <p>Description: {{ Ad.description }}</p>
      <p>Offer Date: {{ Ad.offer_date }}</p>
      <p>Expiry Date: {{ Ad.expiry_date }}</p>
      <p>Stock: {{ Ad.stock_inventory }}</p>
      <p>Category: {{ Ad.category }}</p>
      <p>Address: {{ Ad.address }}</p>
      <p>City: {{ Ad.city }}</p>
      <p>Postal Code: {{ Ad.postal_code }}</p>
    </a>
  </div>
</div>
{% endfor %} {% endblock %}

main_app/templates/growurcoins/testHesham.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>GrowUrCoins</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body>

  <main class="container">
    <form>  


        <label for="category">Category: </label>
        <select  name="category" id="category">
          <option value="P">Please choose an option</option>
          <option value="Lettuce">Lettuce</option>
          <option value="Green Beans">Green Beans</option>
          <option value="Peas">Peas</option>
          <option value="Carrots">Carrots</option>
          <option value="Cucumbers">Cucumbers</option>
          <option value="Kale">Kale</option>
          <option value="Tomatoes">Tomatoes</option>
        </select>

  <div class="input-field col s12">
    <select multiple>
      <option value="" disabled selected>Choose your option</option>
      <option value="1">Option 1</option>
      <option value="2">Option 2</option>
      <option value="3">Option 3</option>
    </select>
    <label>Materialize Multiple Select</label>
  </div>

  </form>
  </main>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

  <script>
    document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems);
  });

  </script>
</body>
</html>

main_app/templates/growurcoins/thankyou.html
{% extends 'base.html' %} 
{% block content %}

<p>Thank you for your order, your total was  ${{  total_coins   }}</p>
<br>
<br>
  <button>
    {% csrf_token %}
     <!-- <button>Delete</button> -->
     <a class="green-text text-darken-3" href="{% url 'delete_cart' %}">Click here to go back to the ad listings</a>  
    </button>   
   </form>

{% endblock %}